### ISSUE TITLE
Unhandled exception (occurs on 500 rate limit)

### ISSUE THREAD

**Issue by antonizoon** [jjjake/internetarchive#170] opened 2016-12-05 22:36 UTC
Mysteriously, on internetarchive 1.10: sometimes and at random points we get an xml.parsers.expat.ExpatError, indicating that the parser was unable to process some kind of output it got back. Is there an unhandled non-XML error being spit out by the Internet Archive API or something?

(Update: it was actually an unhandled HTTP 500 error response, see comment below)

```
[user@localhost ~]$ ia upload warc-www_cfaluminum_com www.cfaluminum.com-2016-12-04-d7f9e3e3/ --metadata="title:WARC: www.cfaluminum.com" --metadata="subject:w arcarchives;aluminum;montana;company;production"                                
warc-www_cfaluminum_com:
 uploading /all_start_urls: [################################] 1/1 - 00:00:00
 uploading /www.cfaluminum.com-2016-12-04-d7f9e3e3-meta.warc.gz: [################################] 1/1 - 00:00:00
 uploading /start_url: [################################] 1/1 - 00:00:00
 uploading /wpull.log: [################################] 9/9 - 00:00:01
 uploading /concurrency: [################################] 1/1 - 00:00:00
 uploading /www.cfaluminum.com-2016-12-04-d7f9e3e3-00000.warc.gz: [################################] 251/251 - 00:00:24
 uploading /max_content_length: [################################] 1/1 - 00:00:00
 uploading /id: [################################] 1/1 - 00:00:00
 uploading /wpull.db: [################################] 6/6 - 00:00:01
 uploading /cookies.txt: [################################] 1/1 - 00:00:00
 uploading /www.cfaluminum.com-2016-12-04-d7f9e3e3.cdx: [################################] 6/6 - 00:00:01
 uploading /igsets: [################################] 1/1 - 00:00:00
Traceback (most recent call last):
  File "/home/gazlene/.local/lib/python3.4/site-packages/internetarchive/item.py", line 625, in upload_file
    response.raise_for_status()
  File "/home/gazlene/.local/lib/python3.4/site-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://s3.us.archive.org/warc-www_cfaluminum_com/ignores

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/ia", line 11, in <module>
    sys.exit(main())
  File "/home/gazlene/.local/lib/python3.4/site-packages/internetarchive/cli/ia.py", line 155, in main
    sys.exit(ia_module.main(argv, session))
  File "/home/gazlene/.local/lib/python3.4/site-packages/internetarchive/cli/ia_upload.py", line 209, in main
    for _r in _upload_files(item, files, upload_kwargs):
  File "/home/gazlene/.local/lib/python3.4/site-packages/internetarchive/cli/ia_upload.py", line 78, in _upload_files
    response = item.upload(files, **upload_kwargs)
  File "/home/gazlene/.local/lib/python3.4/site-packages/internetarchive/item.py", line 719, in upload
    request_kwargs=request_kwargs)
  File "/home/gazlene/.local/lib/python3.4/site-packages/internetarchive/item.py", line 638, in upload_file
    msg = get_s3_xml_text(exc.response.content)
  File "/home/gazlene/.local/lib/python3.4/site-packages/internetarchive/utils.py", line 172, in get_s3_xml_text
    p = parseString(xml_str)
  File "/usr/lib64/python3.4/xml/dom/minidom.py", line 1970, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib64/python3.4/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib64/python3.4/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 49
```

**Comment by antonizoon** [comment] 2016-12-05 22:45
Actually, looking deeper there is also an unhandled 500 requests error (`requests.exceptions.HTTPError: 500 Server Error: Internal Server Error`), which is not as obvious to a user. Maybe it's like a rate limit? 

Generally the ia script handles this 500 error exception by stating that directly, but it wasn't caught in this case. For better debugging, maybe the exception should be caught and state "503 slow down" like it used to do, which is easier for a normal user to understand.

**Comment by jjjake** [comment] 2016-12-05 22:51
Thanks for the report @antonizoon.

Note that the IA-S3 status code for rate-limiting is 503, not 500. Also, `ia` and `internetarchive` only retry on 503 errors (i.e. not 500s).

We're still looking into the cause of this issue, but it is widespread and not limited to this library. Hopefully we can get it sorted shortly.

There is another issue here -- `ia` should fail with a more informative error. I'll file a separate issue for that right now.

I'm going to close this for now, but if you're still having issues several hours from now let me know and I'll reopen it.

**Closed by jjjake** 2016-12-05 22:51 UTC
