### ISSUE TITLE
Breaks with python3 because backports.csv are only available for python2

### ISSUE THREAD

**Issue by yurivict** [jjjake/internetarchive#237] opened 2018-03-11 01:16 UTC
```
pkg_resources.DistributionNotFound: The 'backports.csv' distribution was not found and is required by internetarchive
```

**Comment by jjjake** [comment] 2018-03-12 17:39
How did you attempt to install `internetarchive`?

I'm able to install `internetarchive` and `backports.csv` on both Python 3.4 and 3.6.

Any further details you're able to provide will be helpful. I'm having trouble replicating this issue. Thanks for the report!

**Comment by yurivict** [comment] 2018-03-12 17:50
I am working on the FreeBSD port. backports.csv on the FreeBSD is specifically for python2, because by its definition it back-ports something from python3 to python2. The linux distro that you use missed this, and has it enabled on pythin3 by mistake.

**Comment by jjjake** [comment] 2018-03-12 17:59
I would consider this a bug in the FreeBSD port. While it's intended for Python2, the library is designed so that both py2 and py3 can be supported with:

```from backports import csv```

I can look into making it more flexible (i.e. `Try: import ...`), but want to make sure there's no unintended consequences.

I really think this should be addressed in the FreeBSD port, as `backports.csv` doesn't sound like it's working on FreeBSD as intended (https://github.com/ryanhiebert/backports.csv/blob/master/src/backports/csv.py#L29). I understand if that's not possible for whatever reason though, and can try to make `internetarchive` workaround the bug. I imagine other libraries that support both py2 and py3, and make use of `backports.csv`, will run into this same issue though.

**Comment by ethus3h** [comment] 2018-03-12 21:37
Not sure what GNU/Linux distribution you looked at, so this might be redundant, but I can confirm that Gentoo also ships backports-csv for both Python 2 and Python 3: https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/backports-csv/backports-csv-1.0.5.ebuild

**Comment by yurivict** [comment] 2018-03-12 22:01
I found only one other FreeBSD port that uses ```backports.csv```: ```devel/py-cli-helpers```. It does this:

```
PY2 = sys.version_info[0] == 2
if PY2:
    from backports import csv
else:
   import csv
```

Since backports is specifically created for compatibility with python2, this seems to be right way, vs. just using backports everywhere regardless.

**Comment by yurivict** [comment] 2018-03-12 22:02
And yes, Gentoo port has this bug that it allows backports for python3. Things should be done the right way. -)

**Comment by jjjake** [comment] 2018-03-12 23:06
I'm not sure that I agree with you that your way is the right way, @yurivict, but it should be harmless to patch `internetarchive` to be more flexible.

Feel free to send a PR.

**Comment by yurivict** [comment] 2018-03-13 03:14
https://github.com/jjjake/internetarchive/pull/238

**Comment by jjjake** [comment] 2018-03-13 17:19
Merged. Next time make sure to run the tests (there is some pep8 cleanup I'll have to do.).

Thanks!

**Closed by jjjake** 2018-03-13 17:19 UTC

**Comment by yurivict** [comment] 2018-03-13 17:22
Ok, thanks!
