### ISSUE TITLE
Creator field in metadata seems not to be flushed in bulk upload

### ISSUE THREAD

**Issue by annelhote** [jjjake/internetarchive#182] opened 2017-02-14 10:54 UTC
I try to use internetarchive lib in CLI to bulk upload my files ([https://internetarchive.readthedocs.io/en/latest/cli.html#bulk-uploading](https://internetarchive.readthedocs.io/en/latest/cli.html#bulk-uploading)) with the metadata as a CSV file but the creator field seems not to be flushed between the different uploads :
[https://archive.org/details/EL033_P_1965_003_TEST29](https://archive.org/details/EL033_P_1965_003_TEST29)

Maybe linked to this [https://github.com/jjjake/internetarchive/issues/179](bug) ?

Many thanks !!!

**Comment by jjjake** [comment] 2017-04-11 18:03
Thanks @annelhote.

I'm not sure I understand what the issue is -- is it that the creator field is the same for each item even though the rows on the spreadsheet have different creators? Either way, would you mind emailing or linking me your spreadsheet? Thanks again!

**Comment by jjjake** [comment] 2017-04-25 18:19
I'm closing this for now, we can reopen if more details are provided.

**Closed by jjjake** 2017-04-25 18:19 UTC
